AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: |
  indieauth
  Sample SAM Template for indieauth
Parameters:
  HostedZoneName:
    Type: String
  CognitoSubdomain:
    Type: String
  CertificateArn:
    Type: String
  EmailSender:
    Type: String
Globals:
  Function:
    Timeout: 3
Resources:
  UserPool:
    Type: 'AWS::Cognito::UserPool'
    Properties:
      AdminCreateUserConfig:
        AllowAdminCreateUserOnly: true
      UsernameAttributes:
        - email
      EmailConfiguration:
        EmailSendingAccount: DEVELOPER
        SourceArn:
          'Fn::Sub': 'arn:aws:ses:${AWS::Region}:${AWS::AccountId}:identity/${EmailSender}'
  UserPoolDomain:
    Type: 'AWS::Cognito::UserPoolDomain'
    Properties:
      UserPoolId:
        Ref: UserPool
      Domain:
        'Fn::Sub': '${CognitoSubdomain}.${HostedZoneName}'
      CustomDomainConfig:
        CertificateArn:
          Ref: CertificateArn
