AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: |
  indieauth
  Sample SAM Template for indieauth
Globals:
  Function:
    Timeout: 3
    Environment:
      Variables:
        CMK:
          Ref: IndieAuthCMK
        UserPoolID:
          Ref: UserPool
        UserPoolURL:
          'Fn::GetAtt':
            - UserPool
            - ProviderURL
Resources:
  IndieAuthCMK:
    Type: 'AWS::KMS::Key'
    Properties:
      KeyPolicy:
        Id: DefaultKmsPolicy
        Version: '2012-10-17'
        Statement:
          - Sid: Enable IAM User Permissions
            Effect: Allow
            Principal:
              AWS:
                - 'Fn::Join':
                    - ':'
                    - - 'arn:aws:iam:'
                      - Ref: 'AWS::AccountId'
                      - root
                - '*'
            Action: 'kms:*'
            Resource: '*'
          - Sid: Allow decrypting of any value encrypted under this key.
            Effect: Allow
            Principal:
              AWS:
                - 'Fn::GetAtt':
                    - DecryptAnythingRole
                    - Arn
            Action:
              - 'kms:Decrypt'
            Resource: '*'
          - Sid: Allow encrypting under this key.
            Effect: Allow
            Principal:
              AWS:
                - 'Fn::GetAtt':
                    - EncryptAnythingRole
                    - Arn
            Action:
              - 'kms:Encrypt'
              - 'kms:GenerateDataKey'
            Resource: '*'
  IndieAuthCMKAlias:
    Type: 'AWS::KMS::Alias'
    Properties:
      AliasName: alias/IndieAuth
      TargetKeyId:
        Ref: IndieAuthCMK
  UserPool:
    Type: 'AWS::Cognito::UserPool'
  IndieAuthClient:
    Type: 'AWS::Cognito::UserPoolClient'
    Properties:
      UserPoolId:
        Ref: UserPool
      GenerateSecret: true
  AuthEndpointFunction:
    Type: 'AWS::Serverless::Function'
    Properties:
      CodeUri: auth/
      Handler: app.auth_handler
      Runtime: python3.6
      Events:
        AuthEndpointGET:
          Type: Api
          Properties:
            Path: /auth
            Method: get
      Description: ''
  CallbackEndpointFunction:
    Type: 'AWS::Serverless::Function'
    Properties:
      CodeUri: auth/
      Handler: app.callback_handler
      Runtime: python3.6
      Events:
        CallbackEndpointGET:
          Type: Api
          Properties:
            Path: /callback
            Method: get
  AuthCodeCheckFunction:
    Type: 'AWS::Serverless::Function'
    Properties:
      CodeUri: auth/
      Handler: app.auth_code_check
      Runtime: python3.6
      Events:
        AuthEndpointPOST:
          Type: Api
          Properties:
            Path: /auth
            Method: post
  DecryptAnythingRole:
    Type: 'AWS::IAM::Role'
    Metadata:
      Comment: >-
        DecryptAnythingRole permits decryption of values encrypted under a KMS
        key without any restrictions.
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - ec2.amazonaws.com
            Action:
              - 'sts:AssumeRole'
  EncryptAnythingRole:
    Type: 'AWS::IAM::Role'
    Metadata:
      Comment: >-
        EncryptAnythingRole permits encryption of values under a KMS key without
        any restrictions.
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - ec2.amazonaws.com
            Action:
              - 'sts:AssumeRole'
Outputs:
  AuthEndpoint:
    Description: API Gateway endpoint URL for Prod auth endpoint
    Value:
      'Fn::Sub': >-
        https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/auth
  CallbackEndpoint:
    Description: API Gateway endpoint URL for Prod callback endpoint
    Value:
      'Fn::Sub': >-
        https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/callback
